# Lab Assignment 1
Python Libraries: NumPy & Pandas



**Objective:** This lab assignment will help you gain experience with two essential libraries in Python: NumPy and Pandas. You’ll practice creating and manipulating arrays with NumPy and importing, selecting, and manipulating data with Pandas.


**Instructions:**

1. Follow the tasks listed below.
2. Write your code in the provided cells under each task.
3. When you have completed the assignment, go to File => Download.ipynb to save your notebook
4. Submit your assignment via email following the submission guidelines below.



## **Numpy**

### Formula Sheet for NumPy Library

Arrays are another name for lists

1.   **Creating an array of zeros:** np.zeros(shape)
2.   **Creating an array of ones:** np.ones(shape)
3.   **Creating an array of numbers:** np.arange(start, end, jump)
4.   **Reshaping an array:** array.reshape(new_shape)
5.   **Slicing an array:** array[start:stop]
6.   **Getting the shape of an array:** np.shape(array)

In [1]:
import numpy as np

1. Create two 1D Numpy Lists.

*   *list1* is a list of numbers from 0 to 10
*   *list2* is a list of 10 zeros



In [6]:
list1 = np.arange(0,10,1)
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
list2 = np.zeros(10)
list2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Combine these lists into one lists called *list3*

In [8]:
list3 = list1 + list2
list3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

3. From *list3*, create a new array that includes elements from the 5th to 9th position.

In [9]:
list3[5:9]

array([5., 6., 7., 8.])

4. Change the shape of *list3* to become a 5x2 2D array

In [10]:
list3.reshape(5,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

5. Print the shape of this the following 2D array: *list4*

In [13]:
list4 = [[1,2,3],[4,5,6],[7,8,9]]

np.shape(list4)

(3, 3)

## **Pandas**

### Formula Sheet for NumPy Library
1. **Importing a CSV file:** pd.read_csv('file_path')
2. **Displaying first n rows:** table.head(n)
3. **Selecting a column:** table['column_name']
4. **Changing a DataFrame value:** table.loc[row_index, 'column_name'] = new_value

In [14]:
import pandas as pd

1. Import the *salary.csv* file

In [15]:
df = pd.read_csv("Downloads\salary.csv")
df

Unnamed: 0   District    Salary  Age        English  \
0               0   Brooklyn  120000.0   31  Only language   
1               1   Brooklyn   45000.0   28  Only language   
2               2  Manhatten   85000.0   54  Only language   
3               3  Manhatten   12000.0   45  Only language   
4               4   Brooklyn       0.0   75      Very well   
...           ...        ...       ...  ...            ...   
59432       59432   Brooklyn       0.0   35      Very well   
59433       59433     Queens       0.0   89  Only language   
59434       59434      Bronx       0.0   34  Only language   
59435       59435  Manhatten       0.0   61  Only language   
59436       59436      Bronx   21000.0   25  Only language   

                 Education  Gender  
0          Academic degree    Male  
1          Academic degree  Female  
2          Academic degree    Male  
3      High school diploma  Female  
4          Academic degree  Female  
...                    ...     ...  
59432           No diploma  Female  
59433           No diploma  Female  
59434           No diploma    Male  
59435           No diploma  Female  
59436  High school diploma    Male  

[59437 rows x 7 columns]

2. Display the first 10 rows of the table

In [16]:
df.head(10)

Unnamed: 0   District    Salary  Age        English            Education  \
0           0   Brooklyn  120000.0   31  Only language      Academic degree   
1           1   Brooklyn   45000.0   28  Only language      Academic degree   
2           2  Manhatten   85000.0   54  Only language      Academic degree   
3           3  Manhatten   12000.0   45  Only language  High school diploma   
4           4   Brooklyn       0.0   75      Very well      Academic degree   
5           5  Manhatten  225000.0   47      Very well      Academic degree   
6           6   Brooklyn   55000.0   37  Only language      Academic degree   
7           7   Brooklyn   50000.0   37  Only language      Academic degree   
8           8   Brooklyn   37000.0   34  Only language      Academic degree   
9           9   Brooklyn   65000.0   34  Only language  High school diploma   

   Gender  
0    Male  
1  Female  
2    Male  
3  Female  
4  Female  
5    Male  
6  Female  
7    Male  
8  Female  
9    Male

3. Select the *Age* column and display it

In [17]:
df['Age']

0        31
1        28
2        54
3        45
4        75
         ..
59432    35
59433    89
59434    34
59435    61
59436    25
Name: Age, Length: 59437, dtype: int64

4. Change the 5th value in the *Gender* column.

In [18]:
df.loc[4,'Gender']='Male'

In [19]:
df

Unnamed: 0   District    Salary  Age        English  \
0               0   Brooklyn  120000.0   31  Only language   
1               1   Brooklyn   45000.0   28  Only language   
2               2  Manhatten   85000.0   54  Only language   
3               3  Manhatten   12000.0   45  Only language   
4               4   Brooklyn       0.0   75      Very well   
...           ...        ...       ...  ...            ...   
59432       59432   Brooklyn       0.0   35      Very well   
59433       59433     Queens       0.0   89  Only language   
59434       59434      Bronx       0.0   34  Only language   
59435       59435  Manhatten       0.0   61  Only language   
59436       59436      Bronx   21000.0   25  Only language   

                 Education  Gender  
0          Academic degree    Male  
1          Academic degree  Female  
2          Academic degree    Male  
3      High school diploma  Female  
4          Academic degree    Male  
...                    ...     ...  
59432           No diploma  Female  
59433           No diploma  Female  
59434           No diploma    Male  
59435           No diploma  Female  
59436  High school diploma    Male  

[59437 rows x 7 columns]

**Submission Guidelines:**

1.   You should strictly complete and send the assignment within 30 minutes
2.   Compose an email to **s.abozid@aou.edu.eg**
3.   The subject of the email should be: **Lab Assignment 1 - Your ID Number**
4.   Attach your completed notebook (.ipynb file) to the email.
5.   Send the email once you’re ready to submit